Repository sdpython/mlstatpy, pull requests merged in 2023-07, with the labels that each got.

#38 Rename master into main
  .github/workflows/documentation.yml
  README.rst
  _doc/sphinxdoc/source/c_algo/gest.rst
  _doc/sphinxdoc/source/conf.py
  _doc/sphinxdoc/source/index.rst
  requirements.txt
  setup.py
Labels: refactoring

#42 Quantization with float 8
  .github/workflows/check_urls.yml
  .gitignore
  CHANGELOGS.rst
  _doc/c_garden/quantization.rst
  _doc/conf.py
  _doc/notebooks/dsgarden/classification_multiple.ipynb
  _doc/notebooks/dsgarden/correlation_non_lineaire.ipynb
  _doc/notebooks/dsgarden/discret_gradient.ipynb
  _doc/notebooks/dsgarden/file_dattente_ex.ipynb
  _doc/notebooks/dsgarden/quantile_regression_example.ipynb
  _doc/notebooks/dsgarden/quantization_f8.ipynb
  _doc/notebooks/dsgarden/regression_lineaire.ipynb
  _doc/notebooks/dsgarden/split_train_test.ipynb
  _doc/notebooks/image/segment_detection.ipynb
  _doc/notebooks/metric/pvalues_examples.ipynb
  _doc/notebooks/metric/roc_example.ipynb
  _doc/notebooks/ml/logreg_voronoi.ipynb
  _doc/notebooks/ml/mf_acp.ipynb
  _doc/notebooks/ml/neural_tree.ipynb
  _doc/notebooks/ml/neural_tree_cost.ipynb
  _doc/notebooks/ml/neural_tree_onnx.ipynb
  _doc/notebooks/ml/piecewise_linear_regression.ipynb
  _doc/notebooks/ml/regression_no_inversion.ipynb
  _doc/notebooks/ml/reseau_neurones.ipynb
  _doc/notebooks/ml/survival.ipynb
  _doc/notebooks/ml/valeurs_manquantes_mf.ipynb
  _doc/notebooks/nlp/completion_profiling.ipynb
  _doc/notebooks/nlp/completion_simple.ipynb
  _doc/notebooks/nlp/completion_trie.ipynb
  _doc/notebooks/nlp/completion_trie_long.ipynb
  requirements-dev.txt
Labels: documentation

#44 Improve documentations
  README.rst
  _doc/index.rst
Labels: documentation

#45 Improves actions
  .github/workflows/check-urls.yml
  .github/workflows/documentation.yml
  .github/workflows/rstcheck.yml
  .github/workflows/wheels-any.yml
  .github/workflows/wheels-linux.yml
  .github/workflows/wheels-mac.yml
  .github/workflows/wheels-windows.yml
Labels: ci
